version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  web:
    image: python:3.11-slim
    working_dir: /web
    command: python -m http.server 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/web
